Repository privy-open-source/design-system, pull requests merged in 2023-02, with the labels that each got.

#389 Feat/foundation typography
  packages/tailwind-preset/basic.js
  packages/tailwind-preset/index.js
  src/.vitepress/config.ts
  src/.vitepress/theme/css/custom.css
  src/components/button/Button.vue
  src/components/text/Text.spec.ts
  src/components/text/Text.vue
  src/components/text/index.md
  src/components/text/index.ts
  src/foundation/colors/index.md
  src/foundation/typography/index.md
Labels: documentation, components

#395 Feat/foundation borders
  src/.vitepress/config.ts
  src/foundation/borders/index.md
  src/foundation/typography/index.md
Labels: documentation

#393 added: add shadow foundation
  src/foundation/shadows/index.md
Labels: documentation

#400 fix(core): add missing exposed composition utils
  .eslintrc.js
  package.json
  packages/browserslist-config/package.json
  packages/browserslist-config/tsconfig.json
  packages/eslint-config-persona/package.json
  packages/eslint-config-persona/tsconfig.json
  packages/persona/.eslintrc
  packages/persona/package.json
  packages/persona/src/runtime/plugin.ts
  packages/persona/tsconfig.json
  packages/tailwind-animation/package.json
  packages/tailwind-animation/tsconfig.json
  packages/tailwind-extended/package.json
  packages/tailwind-extended/tsconfig.json
  packages/tailwind-preset/package.json
  packages/tailwind-preset/tsconfig.json
  src/components/pagination/index.md
  src/core/index.ts
  tsconfig.eslint.json
  yarn.lock
Labels: bug

#404 feat/foundation-variables
  packages/tailwind-preset/basic.js
  src/.vitepress/config.ts
  src/.vitepress/theme/css/custom.css
  src/components/button-group/ButtonGroup.vue
  src/components/button/Button.vue
  src/components/card/Card.vue
  src/components/checkbox/Checkbox.vue
  src/components/dropdown/Dropdown.vue
  src/components/label/Label.vue
  src/components/radio/Radio.vue
  src/components/toggle/Toggle.vue
  src/components/tour/TourHighlight.vue
  src/foundation/borders/index.md
  src/foundation/shadows/index.md
  src/foundation/variables/index.md
  src/styleguide/badge/index.md
  src/styleguide/banner/index.md
  src/styleguide/button-group/index.md
  src/styleguide/button/index.md
  src/styleguide/checkbox-radio/index.md
  src/styleguide/navbar/index.md
Labels: documentation
