Repository privy-open-source/design-system, pull requests merged in 2023-04, with the labels that each got.

#453 feat/banner-slot-icon
  src/components/banner/Banner.spec.ts
  src/components/banner/Banner.vue
  src/components/banner/index.md
Labels: enhancement

#457 feat/table-slot-empty
  packages/tailwind-preset/index.js
  src/components/contextual-bar/index.md
  src/components/sidebar/Sidebar.vue
  src/components/sidebar/SidebarNav.vue
  src/components/table/Table.spec.ts
  src/components/table/Table.vue
  src/components/table/index.md
  src/foundation/colors/Colors.json
  src/public/assets/images/img-contextualbar-bg.svg
  src/public/assets/images/img-table-empty-records.svg
Labels: enhancement

#467 PDFObject: fix addon apperance in dark mode
  packages/persona/package.json
  src/components/contextual-bar/index.md
  src/components/pdf-helipad/PdfHelipad.vue
  src/components/pdf-object/PdfObjectAddon.vue
  src/components/pdf-object/PdfObjectDebugger.vue
  src/components/pdf-object/utils/position.ts
  yarn.lock
Labels: bug

#468 fix/main-typography-permalink
  src/.vitepress/theme/css/custom.css
  src/components/main/Main.vue
Labels: bug

#470 fix(checkbox): check box stretch when has very long caption
  src/components/checkbox/Checkbox.vue
  src/components/form-group/index.md
  src/components/select/index.md
Labels: bug

#472 fix(nav): toggle dropdown via v-model in navItemDropdown
  src/components/nav/NavItemDropdown.spec.ts
  src/components/nav/NavItemDropdown.vue
  src/components/nav/index.md
Labels: enhancement

#473 style: change button color of tour
  src/components/button/index.md
  src/components/tour/TourDialog.vue
Labels: bug

#476 docs/input-prepend-append
  src/components/datepicker/Datepicker.vue
  src/components/form-group/FormGroup.vue
  src/components/input/Input.spec.ts
  src/components/input/Input.vue
  src/components/input/index.md
Labels: documentation, enhancement
