Repository privy-open-source/design-system, pull requests merged in 2023-09, with the labels that each got.

#816 feat(form-group): add support horizontal mode
  src/components/form-group/FormGroup.spec.ts
  src/components/form-group/FormGroup.vue
  src/components/form-group/index.md
Labels: enhancement

#835 feat(dialog): adding options dialog for dismiss and no close dialog
  src/components/dialog/Dialog.vue
  src/components/dialog/index.md
  src/components/dialog/index.ts
Labels: documentation, enhancement

#832 feat(modal): add modal full and modal free distraction
  src/components/modal/Modal.spec.ts
  src/components/modal/Modal.vue
  src/components/modal/index.md
  src/components/modal/index.ts
Labels: documentation, enhancement

#855 feat(text): add element tag in text component
  src/.vitepress/theme/components/Preview.vue
  src/components/button/Button.vue
  src/components/button/index.md
  src/components/text/Text.vue
  src/components/text/index.md
  src/components/text/index.ts
Labels: enhancement

#860 feat(badge): possible to make custom badge color via class
  src/components/badge/Badge.vue
  src/components/badge/index.md
Labels: documentation, enhancement

#863 feat(toggle): add custom switch class
  src/components/toggle/Toggle.spec.ts
  src/components/toggle/Toggle.vue
  src/components/toggle/index.md
Labels: documentation, enhancement

#866 feat(banner): make banner support with no-icon
  src/components/banner/Banner.spec.ts
  src/components/banner/Banner.vue
  src/components/banner/index.md
Labels: documentation, enhancement

#875 fix(main): global heading affected another heading component
  src/components/accordion/AccordionItem.vue
  src/components/card/CardSection.vue
  src/components/main/Main.vue
  src/components/tour/TourDialog.vue
Labels: bug

#864 feat(select): enable option divider, menuClass and menuSize in select
  src/components/select/Select.vue
  src/components/select/index.md
Labels: documentation, enhancement

#876 feat(label): change label padding
  src/components/label/Label.vue
Labels: enhancement

#877 feat(contextualbar): replace variant with state
  src/components/contextual-bar/ContextualBar.spec.ts
  src/components/contextual-bar/ContextualBar.vue
  src/components/contextual-bar/index.md
  src/components/contextual-bar/index.ts
Labels: enhancement

#896 feat(label): possible to insert icon in label and customize label color
  src/components/badge/index.md
  src/components/label/Label.vue
  src/components/label/index.md
Labels: documentation, enhancement

#897 feat(pagination): add select-input sizing
  src/components/pagination/Pagination.vue
  src/components/pagination/index.md
Labels: enhancement

#903 fix(list group): change state of dropdown, select and list group
  src/components/dropdown/DropdownItem.vue
  src/components/dropdown/index.md
  src/components/list-group/ListGroupItem.vue
  src/components/select/Select.vue
Labels: bug
