Repository privy-open-source/design-system, pull requests merged in 2023-03, with the labels that each got.

#403 refactor(pdf-viewer): change initial zoom on wider container
  packages/persona/src/module.ts
  src/components/pdf-object/kitchensink.md
  src/components/pdf-viewer/PdfError.vue
  src/components/pdf-viewer/PdfLoading.vue
  src/components/pdf-viewer/PdfViewer.vue
  src/components/pdf-viewer/__mocks__/use-viewer.ts
  src/components/pdf-viewer/assets/pdf-loading.svg
  src/components/pdf-viewer/index.md
  src/components/pdf-viewer/utils/use-viewer.ts
  src/docs/browser-support.md
Labels: enhancement

#412 Bugfix/table broken with long content
  src/components/dropdown/index.md
  src/components/table/Table.vue
  src/components/table/index.md
Labels: bug

#414 Feat/breadcrumb
  src/.vitepress/config.ts
  src/components/breadcrumbs/Breadcrumb.spec.ts
  src/components/breadcrumbs/Breadcrumb.vue
  src/components/breadcrumbs/BreadcrumbItem.spec.ts
  src/components/breadcrumbs/BreadcrumbItem.vue
  src/components/breadcrumbs/BreadcrumbItemDropdown.spec.ts
  src/components/breadcrumbs/BreadcrumbItemDropdown.vue
  src/components/breadcrumbs/index.md
  src/components/breadcrumbs/index.ts
  src/components/button/Button.spec.ts
  src/components/button/Button.vue
  src/components/button/index.md
  src/components/button/index.ts
  src/components/dropdown/DropdownItem.spec.ts
  src/components/dropdown/DropdownItem.vue
  src/components/dropdown/index.md
Labels: documentation, components

#416 docs/form-select-sizing
  packages/tailwind-preset/index.js
  src/.vitepress/config.ts
  src/components/navbar/Navbar.vue
  src/components/navbar/NavbarNav.vue
  src/components/select/index.md
  src/components/sidebar/Sidebar.vue
  src/components/table/Table.vue
  src/foundation/shadows/index.md
  src/styleguide/check-radio/index.md
  src/styleguide/navigation/index.md
Labels: documentation

#418 docs/styleguide-table
  src/.vitepress/config.ts
  src/components/table/Table.vue
  src/components/table/index.md
  src/components/toggle/Toggle.spec.ts
  src/components/toggle/Toggle.vue
  src/public/assets/images/img-guide-data-table.svg
  src/styleguide/table/index.md
Labels: bug, documentation

#420 docs/styleguide-avatar
  src/.vitepress/config.ts
  src/public/assets/images/img-guide-avatar-redline-24.svg
  src/public/assets/images/img-guide-avatar.svg
  src/styleguide/avatar/index.md
Labels: documentation

#422 docs: (create styleguide for dropdown menu, fix modal backdrop backgr…
  packages/tailwind-preset/basic.js
  src/.vitepress/config.ts
  src/components/camera/Camera.vue
  src/components/divider/Divider.vue
  src/components/dropdown/Dropdown.vue
  src/components/dropdown/DropdownItem.vue
  src/components/input-group/index.md
  src/components/modal/Modal.vue
  src/core/index.ts
  src/public/assets/images/img-guide-dropdown.svg
  src/styleguide/dropdown/index.md
  src/styleguide/table/index.md
Labels: documentation

#425 docs/progress-styleguide
  src/.vitepress/config.ts
  src/public/assets/images/img-guide-progress.svg
  src/styleguide/progress/index.md
Labels: documentation

#427 docs/toggle-styleguide
  src/.vitepress/config.ts
  src/public/assets/images/img-guide-toggle.svg
  src/styleguide/toggle/index.md
Labels: documentation
