Repository privy-open-source/design-system, pull requests merged in 2023-10, with the labels that each got.

#927 feat(nav): nav lines color is follow the brand accent color
  src/components/nav/Nav.vue
  src/components/nav/NavItem.vue
  src/components/tabs/Tabs.vue
Labels: enhancement

#938 fix(dialog): dialog z-index must be higher than modal
  packages/tailwind-preset/index.js
  src/components/dialog/Dialog.vue
Labels: bug

#939 fix(pagination): remove select search in per page options
  src/components/calendar/Calendar.vue
  src/components/pagination/Pagination.spec.ts
  src/components/pagination/Pagination.vue
  src/components/table-static/TableStatic.vue
  src/components/table-static/index.md
Labels: bug

#944 fix: pdf-viewer
  src/components/pdf-viewer/utils/use-viewer.ts
  src/core/index.ts
Labels: bug, components

#946 fix(table): handle empty data non array
  src/components/table-flex/TableFlex.vue
  src/components/table-static/TableStatic.vue
  src/components/table/Table.vue
Labels: bug

#925 fix(layout): some component broken when combined with very long content
  src/components/banner/Banner.vue
  src/components/calendar/Calendar.vue
  src/components/camera/Camera.vue
  src/components/carousel/Carousel.vue
  src/components/carousel/index.md
  src/components/checkbox/Checkbox.vue
  src/components/contextual-bar/ContextualBar.vue
  src/components/cropper/Cropper.vue
  src/components/dropdown-subitem/DropdownSubitem.vue
  src/components/dropdown/Dropdown.vue
  src/components/form-group/FormGroup.vue
  src/components/input-group/InputGroup.vue
  src/components/input-range/InputRange.vue
  src/components/nav/Nav.vue
  src/components/navbar/Navbar.vue
  src/components/navbar/index.md
  src/components/page/page.md
  src/components/pdf-viewer/PdfNavigation.vue
  src/components/pdf-viewer/PdfViewer.vue
  src/components/radio/Radio.vue
  src/components/select/Select.vue
  src/components/select/index.md
  src/components/sidebar/Sidebar.vue
  src/components/sidebar/SidebarNav.vue
  src/components/steps/index.md
  src/components/strengthbar/Strengthbar.vue
  src/components/table-flex/TableFlex.vue
  src/components/table-flex/index.md
  src/components/table/Table.vue
  src/components/toast/Toast.vue
  src/components/toggle/Toggle.vue
  src/components/tour/TourDialog.vue
  src/components/wizard/Wizard.vue
  src/components/wizard/index.md
  src/styleguide/navigation/index.md
Labels: bug

#952 feat(dialog): refine spacing of modal footer button
  src/components/dialog/DialogFooter.vue
  src/components/sidebar/SidebarNav.vue
Labels: bug

#953 fix(table): unchecked select all on table static if no items
  src/components/table-static/TableStatic.spec.ts
  src/components/table-static/TableStatic.vue
  src/components/table/Table.spec.ts
  src/components/table/Table.vue
Labels: Improvement

#943 feat(toast): support markdown and custom icon
  src/components/toast/Toast.spec.ts
  src/components/toast/Toast.vue
  src/components/toast/ToastContainer.spec.ts
  src/components/toast/ToastContainer.vue
  src/components/toast/index.md
  src/components/toast/index.ts
Labels: enhancement

#975 fix(table-static): broken table row in non-scrollable type
  src/components/table-static/TableStatic.vue
  src/components/table-static/index.md
Labels: bug

#976 feat(toast): able to change icon color of toast
  src/components/toast/Toast.spec.ts
  src/components/toast/Toast.vue
  src/components/toast/ToastContainer.vue
  src/components/toast/index.md
  src/components/toast/index.ts
Labels: enhancement

#987 fix(select): select active state styling
  src/components/checkbox/Checkbox.vue
  src/components/dropdown/DropdownItem.vue
  src/components/select/Select.vue
Labels: bug
