Repository privy-open-source/design-system, pull requests merged in 2023-05, with the labels that each got.

#486 fix/permalink-like-button-inappropriate
  src/.vitepress/theme/css/custom.css
  src/components/button/Button.vue
Labels: bug

#487 feat/text-transform-and-text-weight
  src/components/text/Text.spec.ts
  src/components/text/Text.vue
  src/components/text/index.md
Labels: enhancement

#488 docs/foundation-colors-token
  src/foundation/colors/Colors.json
  src/foundation/colors/index.md
Labels: documentation

#497 docs/form-group
  src/components/form-group/index.md
Labels: documentation

#499 bug/input-append-prepend-readonly-onfocus
  src/components/button-group/ButtonGroup.vue
  src/components/input/Input.vue
  src/components/radio/index.md
  src/components/spread/Spread.vue
  src/components/toggle/Toggle.vue
  src/styleguide/check-radio/index.md
Labels: bug

#501 fix/reorganize-zindex-of-components
  packages/tailwind-preset/index.js
  src/components/modal/Modal.vue
  src/components/modal/index.md
  src/components/navbar/Navbar.vue
  src/components/navbar/index.md
  src/components/overlay/Overlay.vue
  src/components/sidebar/Sidebar.vue
  src/components/sidebar/index.md
  src/components/toast/Toast.vue
  src/components/toast/ToastContainer.vue
  src/components/tooltip/Tooltip.vue
  src/components/tour/Tour.vue
  src/components/tour/TourDialog.vue
  src/components/tour/TourHighlight.vue
  src/foundation/variables/index.md
Labels: bug

#500 fix(dropdown): stop downdrop to prevent others tab keyup
  src/components/dropdown/Dropdown.vue
  src/components/dropdown/DropdownItem.vue
  src/components/form-group/index.md
  src/components/form-group/kitchensink.md
Labels: bug

#498 fix/centering-items-inside-navbar-nav
  src/components/dropdown/Dropdown.spec.ts
  src/components/dropdown/Dropdown.vue
  src/components/dropdown/index.md
  src/components/nav/NavItemDropdown.spec.ts
  src/components/nav/NavItemDropdown.vue
  src/components/nav/index.md
  src/components/navbar/NavbarNav.vue
  src/components/navbar/index.md
Labels: bug

#516 fix/sidebar-bottom-menu-overlap
  src/components/pdf-object/kitchensink.md
  src/components/sidebar/Sidebar.vue
  src/components/sidebar/SidebarNav.vue
  src/components/sidebar/index.md
Labels: bug

#520 fix/navigation-button-dissapear-on-focus
  src/components/pdf-viewer/PdfNavigation.vue
Labels: bug

#523 fix/sidebar-brand-and-variable
  src/components/pdf-object/kitchensink.md
  src/components/pdf-object/test.md
  src/components/sidebar-menu/SidebarMenu.vue
  src/components/sidebar/Sidebar.spec.ts
  src/components/sidebar/Sidebar.vue
  src/components/sidebar/SidebarBrand.spec.ts
  src/components/sidebar/SidebarBrand.vue
  src/components/sidebar/index.md
Labels: bug

#535 fix/breadcrumb-text-and-dropdown
  src/components/breadcrumbs/BreadcrumbItem.vue
  src/components/breadcrumbs/BreadcrumbItemDropdown.vue
Labels: bug

#540 feat/navbar-responsive
  src/components/collapse/Collapse.vue
  src/components/nav/NavItemDropdown.vue
  src/components/nav/index.md
  src/components/navbar/Navbar.vue
  src/components/navbar/index.md
Labels: enhancement

#537 feat/dropdown-menu-sizing
  src/components/dropdown/Dropdown.spec.ts
  src/components/dropdown/Dropdown.vue
  src/components/dropdown/index.md
  src/components/dropdown/index.ts
Labels: enhancement
