Repository privy-open-source/design-system, pull requests merged in 2023-07, with the labels that each got.

#600 feat(sidebar): limit menu-item
  src/.vitepress/theme/css/custom.css
  src/components/navbar/Navbar.vue
  src/components/sidebar-menu/SidebarMenu.spec.ts
  src/components/sidebar-menu/SidebarMenu.vue
  src/components/sidebar-menu/index.md
  src/components/sidebar-menu/index.ts
  src/components/sidebar/index.md
  src/components/truncate/index.md
Labels: enhancement

#609 feat(nav): enable divider in nav-item-dropdown
  src/components/dropdown/index.md
  src/components/nav/NavItemDropdown.spec.ts
  src/components/nav/NavItemDropdown.vue
  src/components/nav/index.md
Labels: enhancement

#613 fix/broken-input-in-darkmode
  src/components/input/Input.vue
Labels: bug

#612 feat/dropdown-header
  src/components/checkbox/Checkbox.vue
  src/components/dropdown/Dropdown.spec.ts
  src/components/dropdown/Dropdown.vue
  src/components/dropdown/DropdownHeader.spec.ts
  src/components/dropdown/DropdownHeader.vue
  src/components/dropdown/index.md
  src/components/radio/Radio.vue
  src/styleguide/dropdown/index.md
Labels: documentation, components

#622 feat/dropdown-header-action
  src/components/dropdown/Dropdown.vue
  src/components/dropdown/DropdownHeader.spec.ts
  src/components/dropdown/DropdownHeader.vue
  src/components/dropdown/index.md
  src/components/nav/NavItem.vue
  src/components/nav/NavItemDropdown.vue
Labels: enhancement

#625 feat/list-group
  src/.vitepress/config.ts
  src/.vitepress/theme/css/custom.css
  src/components/card/Card.vue
  src/components/list-group/ListGroup.spec.ts
  src/components/list-group/ListGroup.vue
  src/components/list-group/ListGroupItem.spec.ts
  src/components/list-group/ListGroupItem.vue
  src/components/list-group/index.md
  src/components/list-group/index.ts
  src/components/table/index.md
Labels: documentation, components

#620 feat(sidebar): add access in each menu item
  src/components/sidebar-menu/index.md
  src/components/sidebar-menu/index.ts
Labels: enhancement

#630 fix/input-password-clearable
  src/components/input-password/InputPassword.vue
  src/components/input-password/index.md
Labels: bug

#636 fix/component-with-link-overwritten-by-main-permalink-style
  src/components/main/Main.vue
Labels: bug

#646 feat/component-variables
  src/components/button/Button.vue
  src/components/button/index.md
  src/components/modal/Modal.vue
  src/components/modal/index.md
  src/components/tabs/Tabs.vue
  src/components/tabs/index.md
Labels: enhancement

#656 Feat/add total steps
  src/components/steps/Step.vue
  src/components/steps/Steps.vue
  src/components/steps/index.md
  src/components/steps/index.ts
Labels: documentation, components

#662 fix(toast): balancing margin of toast in all position variant
  src/components/toast/ToastContainer.vue
Labels: bug

#653 Docs: add docs for using custom option with slot
  src/components/select/index.md
Labels: documentation

#663 feat(input): adding container class in input-text and input password
  src/components/input-password/index.md
  src/components/input/Input.spec.ts
  src/components/input/Input.vue
  src/components/input/index.md
Labels: enhancement

#665 feat(list group): add borderless and rounded variant in list group
  src/components/list-group/ListGroup.spec.ts
  src/components/list-group/ListGroup.vue
  src/components/list-group/index.md
Labels: documentation, enhancement

#666 fix(pin-input): fix inconsistent `deleteContentBackward` on safari
  src/components/datepicker/Datepicker.spec.ts
  src/components/datepicker/Datepicker.vue
  src/components/datepicker/index.md
  src/components/input-pin/InputPin.spec.ts
  src/components/input-pin/InputPin.vue
Labels: bug

#672 docs: add centered props to modal docs
  src/components/modal/index.md
Labels: documentation

#674 docs: add field props in table props api
  src/components/table/index.md
Labels: documentation

#677 feat(card): add custom variables for card
  src/components/card/Card.vue
  src/components/card/index.md
  src/components/sidebar-menu/index.ts
  src/components/toggle/Toggle.vue
Labels: enhancement

#687 feat(filterbar): replace section label with dropdown header
  src/components/filterbar/pinned/PinnedDate.vue
  src/components/filterbar/pinned/PinnedMultiselect.vue
  src/components/filterbar/pinned/PinnedSelect.vue
Labels: bug

#715 fix(signature-draw): fix button wrong position when loaded on ssr
  src/components/avatar/utils/create-image.spec.ts
  src/components/avatar/utils/create-image.ts
  src/components/signature-draw/SignatureDrawMobile.vue
Labels: bug

#684 feat(select): add section label in select container
  src/components/select/Select.spec.ts
  src/components/select/Select.vue
  src/components/select/index.md
Labels: enhancement
