Repository privy-open-source/design-system, pull requests merged in 2024-09, with the labels that each got.

#1414 fix: refine button variant variable
  src/components/button/Button.vue
  src/components/navbar/Navbar.vue
Labels: enhancement

#1445 Fix/refine button
  packages/tailwind-preset/index.js
  src/components/button/Button.vue
  src/components/button/index.md
  src/components/button/index.ts
  src/components/navbar/Navbar.vue
  src/foundation/colors/Colors.json
Labels: documentation, Improvement

#1419 feat(avatar): create avatar square-round type variant
  src/components/accordion/Accordion.vue
  src/components/accordion/AccordionItem.vue
  src/components/accordion/index.md
  src/components/avatar/Avatar.spec.ts
  src/components/avatar/Avatar.vue
  src/components/avatar/index.md
  src/components/notify/NotifyGroup.vue
  src/components/toast/index.md
Labels: documentation, enhancement, components

#1463 fix(select): fix selected values when option items updated after search
  src/components/select/Select.spec.ts
  src/components/select/Select.vue
  src/components/select/index.md
Labels: bug

#1476 feat: create placement for datepicker
  src/components/datepicker/Datepicker.vue
  src/components/datepicker/index.md
Labels: documentation, enhancement

#1475 refine card
  src/components/button/Button.vue
  src/components/button/index.md
  src/components/card/Card.spec.ts
  src/components/card/Card.vue
  src/components/card/index.md
  src/components/card/index.ts
Labels: documentation, enhancement
